---
title: "Tables of Birth Statistics for WI Counties"
author: "Chris Gottwaldt"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(dplyr)
library(knitr)
library(kableExtra)
```

```{r, echo=FALSE, message=FALSE}
births = read_csv("https://uwmadison.box.com/shared/static/xgwpsw0nx2gniuof4okacl9d8huu4v3v.csv")
```

<center> <h1>Top 10 WI Counties by Total Births</h1> </center>

```{r}
# table for top 10 highest total birth counties
top_births = births %>%
  filter(county != "Total") %>%
  arrange(desc(total_births)) %>%
  reframe(
    "County" = county,
    "Total Births" = total_births,
    "Female Babies" = f_births,
    "Male Babies" = m_births,
    "Crude Birth Rate" = crude_birth_rate
  )%>%
  slice_head(n = 10)

# format as a kableExtra table, just keep top 10
top_births %>%
  kbl() %>%
  kable_paper("hover", full_width = F)
```

<center> <h1>Top 10 WI Counties by Fertility Rate</h1> </center>

```{r}
# table for top 10 highest fertility rate counties
top_fertility = births %>%
  filter(county != "Total") %>%
  arrange(desc(fertility_rate)) %>%
  reframe(
    "County" = county,
    "Fertility Rate" = fertility_rate,
    "Total Births" = total_births,
    "Female Babies" = f_births,
    "Male Babies" = m_births
  )%>%
  slice_head(n = 10)

# format as a kableExtra table, just keep top 10
top_fertility %>%
  kbl() %>%
  kable_paper("hover", full_width = F)
```







