```{r}
library(ggplot2)
library(shiny)
library(dplyr)
library(tidyr)
library(readr)

births = read_csv('2022birthdataWiscIteration2.csv')
births <- births %>%
  mutate(across(-county, ~ifelse(. == "<5", "0", as.character(.)))) %>%
  mutate(across(-county, as.numeric))

```

```{r}
births = read_csv('2022birthdataWiscIteration2.csv')
births <- births %>%
  mutate(across(-county, ~ifelse(. == "<5", "0", as.character(.)))) %>%
  mutate(across(-county, as.numeric))
```

```{r}
ui <- fluidPage(
  titlePanel("Births by Mother's Ethnicity in Selected County"),
  sidebarLayout(
    sidebarPanel(
      selectInput("selectedCounty", "Select a County:", choices = births$county)
    ),
    mainPanel(
      plotOutput("ethnicityPlot")
    )
  )
)


server <- function(input, output) {
  output$ethnicityPlot <- renderPlot({
    
    filtered_data <- filter(births, county == input$selectedCounty)
    
   
    long_data <- pivot_longer(filtered_data, 
                              cols = starts_with("mother_ethnicity"), 
                              names_to = "Ethnicity", 
                              values_to = "Births")
    
    
    long_data$Ethnicity <- sub("mother_ethnicity_", "", long_data$Ethnicity)
    
    
    ggplot(long_data, aes(x = Ethnicity, y = Births, fill = Ethnicity)) +
      geom_bar(stat = "identity") +
      theme_minimal() +
      labs(title = paste("Distribution of Births by Ethnicity in", input$selectedCounty),
           x = "Ethnicity", y = "Number of Births") +
      theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
  })
}


shinyApp(ui, server )

```





